### ISSUE TITLE
是否考虑添加设置background接口？

### ISSUE THREAD

**Issue by bawuju** [cpiz/BubbleView#10]
比如我现在需要的气泡背景是渐变的颜色，这样的话单独设置color就无法做到渐变了。
如果给气泡设置成透明，然后子view设置渐变的background，那箭头也就变的透明了（箭头不算子view）。
看了看源码，setColor是直接作用在paint上，所以不知道是否考虑会加上background？
thx.

**Comment by bawuju** [comment]
使用paint.setShader()

**Comment by cpiz** [comment]
这个特性对现有实现改动较大，暂时不会考虑
