### ISSUE TITLE
setpadding效果有点问题

### ISSUE THREAD

**Issue by SmallDream** [cpiz/BubbleView#12]
`public void showArrowTo(View anchor, RelativePos relativePos, int marginH, int marginV) {
        dismiss();

        final int screenWidth = Resources.getSystem().getDisplayMetrics().widthPixels;
        final int screenHeight = Resources.getSystem().getDisplayMetrics().heightPixels;
        final int navigationBarHeight = getNavigationBarHeightDelta(anchor);
        final Rect anchorRect = getRectInWindow(anchor);

        getContentView().measure(
                View.MeasureSpec.makeMeasureSpec(screenWidth - 2 * mPadding, View.MeasureSpec.AT_MOST),
                View.MeasureSpec.makeMeasureSpec(screenHeight - 2 * mPadding, View.MeasureSpec.AT_MOST));
        final int contentWidth = getContentView().getMeasuredWidth();
        final int contentHeight = getContentView().getMeasuredHeight();
        Log.d(TAG, String.format("w:%d, h:%d", contentWidth, contentHeight));

        PopupProp outProp = new PopupProp();
        getPopupProp(screenWidth, screenHeight, navigationBarHeight, anchorRect, contentWidth, contentHeight, relativePos, marginH, marginV, mPadding, outProp);

        setWidth(ViewGroup.LayoutParams.WRAP_CONTENT);
        setHeight(ViewGroup.LayoutParams.WRAP_CONTENT);
        setAnimationStyle(outProp.animationStyle);
        if (contentWidth > outProp.maxWidth) {
            setWidth(outProp.maxWidth);
        }
        mBubbleView.setArrowDirection(outProp.direction);
        mBubbleView.setArrowPosPolicy(outProp.arrowPosPolicy);
        mBubbleView.setArrowTo(anchor);
        mBubbleView.setArrowPosDelta(mArrowPosDelta);
        showAtLocation(anchor, outProp.gravity, outProp.x, outProp.y);

        if (mDelayMillis > 0) {
            setCancelOnLater(mDelayMillis);
        }
    }`

其中if (contentWidth > outProp.maxWidth) {
            setWidth(outProp.maxWidth);
        }
这行代码无效，我padding设置成很大， outProp.maxWidth 只有100多，可最终显示出来还是900多的宽。

另外可否添加类似setpadding(top,left,right.bottom)来支持更多的定制化

**Comment by cpiz** [comment]
抱歉，需要你测试的源码才好判断问题，最好也有截图。
