### ISSUE TITLE
BubbleXXX 的內容不是在气泡中心

### ISSUE THREAD

**Issue by DanteAndroid** [cpiz/BubbleView#16]
通过调节 padding 可以使之在中心，但是这样做有两个问题：
1. 这样调节不准确
2. 如果写死 padding，某个箭头方向可能内容大概在中心位置了，但是当箭头方向动态改变时，内容还是不会在气泡中心。

**Comment by DanteAndroid** [comment]
找到问题所在了，是因为我在 xml 中配置了 `app:bb_arrowDirection="Up"` 后又动态设置了箭头方向导致内容不在中心。去掉这个属性只用代码设置就没问题。请问为什么呢？

**Comment by cpiz** [comment]
BubbleView本身是一个容器，推荐用gravity或其他layout的属性来指定内容居中，用padding调整则很难达到效果。

由于箭头的存在，为了让内容居中在气泡的中央，在BubbleView的内部实现中实际是在箭头方向增加了额外的padding来实现的。两次指定箭头方向可能导致额外的padding没有去除，导致了错误。
