### ISSUE TITLE
不知道为什么用了之后，有个手机报找不到drawable-xhdpi-v4的错误，这个项目有用到这个目录吗？

### ISSUE THREAD

**Issue by axkza** [cpiz/BubbleView#17]
Caused by java.io.FileNotFoundException: res/drawable-xhdpi-v4/bubble_icon_feed.png

**Comment by cpiz** [comment]
这个应该是编译的问题或者手机本身的错误，代码都是开源的，可以看到并没有什么特别的资源使用。
