### ISSUE TITLE
添加依赖失败 ERROR: Failed to resolve: com.cpiz

### ISSUE THREAD

**Issue by AaarnoldHuang** [cpiz/BubbleView#20]
你好，我已经按照README中的要求在 项目目录的 build.gradle 中增加 jcenter()
在模块目录的 build.gradle 中增加 
    implementation 'com.cpiz.bubbleview:bubbleview:{1.0.3}'
但是sync一直出现问题，
**ERROR: Failed to resolve: com.cpiz
Affected Modules: app**

请问是怎么了？

**Comment by liweijieok** [comment]
我目前也是
```
ERROR: Failed to resolve: com.cpiz.bubbleview:bubbleview:1.0.3
Show in Project Structure dialog
Affected Modules: app, base, tcp

```
依赖方式：
```
api 'com.cpiz.bubbleview:bubbleview:1.0.3'
```
根目录已经添加了
```
 repositories {
        google()

        maven { url "https://jitpack.io" }
        jcenter()
    }
```
以及添加了class path
```
classpath 'com.android.tools.build:gradle:3.3.2'
 classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath "org.jacoco:org.jacoco.core:0.8.2"
```

**Comment by FhrShadow** [comment]
我注意到在maven上该项目的最新版本为1.0.2，用1.0.2版本试试
↓maven地址↓
https://mvnrepository.com/artifact/com.cpiz.bubbleview/bubbleview/1.0.2

**Comment by sohnyi** [comment]
使用 JCenter 可以添加 1.0.3 版本

**Comment by forzajuve** [comment]
添加了jcenter()，我也是1.0.3的下不下来，1.0.2的就可以
