### ISSUE TITLE
BubbleView的动态设置可行性问题

### ISSUE THREAD

**Issue by rehan91** [cpiz/BubbleView#3]
hello,我打算在一个柱状图中使用这个控件,但是不知道这个控件能不能实时的设置显示或者消失,我希望可以在点击一个柱体的时候显示在柱体上方,点击另一个柱体的时候原先的View消失,当前柱体上方显示View,同理,其他也一样,不知是否可行?也就是说,我需要的是这个View的位置是不固定的,并不是在布局中写死的.

**Comment by cpiz** [comment]
你的需求是想要BubbleView跟随当前的柱体，这个逻辑和BubbleView本身并没有关系，应该自行实现。

两种方法：
1.自行改变BubbleView的位置，移动到不同的柱体上
2.在每个柱体上方摆放一个BubbleView，切换不同柱体时隐藏/显示

**Comment by rehan91** [comment]
額,这个当初也是我想过的,但是不够便捷,最终自己封装写了一个控件来实现.
