### ISSUE TITLE
使用BubbleLinearLayout+BubblePopupWindow显示气泡框，怎样能和父窗口预留距离

### ISSUE THREAD

**Issue by easionchang** [cpiz/BubbleView#5]
使用BubbleLinearLayout+BubblePopupWindow显示气泡框，怎样能和父窗口预留距离，如图所示，气泡框左边贴近窗口，怎样设置空余位置
[http://share.weiyun.com/36c0b357c01df4a294ac2dd804b6b0b5](url)

**Comment by cpiz** [comment]
刚才给 BubblePopupWindow 增加了一个 setPadding 方法，试试看
