### ISSUE TITLE
如何单独修改箭头颜色

### ISSUE THREAD

**Issue by i-rtfsc** [cpiz/BubbleView#6]
请问如何单独修改箭头颜色？

**Comment by cpiz** [comment]
这个需求好奇怪啊，不怕难看吗？

**Comment by i-rtfsc** [comment]
是有点怪，但是只是知道是否有什么属性可以直接设置？

**Comment by cpiz** [comment]
没考虑过这个场景，而且箭头变色涉及框线的颜色和填充的颜色。没有特别需要的话，以后也不会考虑。
