### ISSUE TITLE
添加项目依赖出现问题

### ISSUE THREAD

**Issue by peterforme** [cpiz/BubbleView#7]
我在项目目录的 build.gradle 中增加 maven { url "https://jitpack.io" }
在模块目录的 build.gradle 中增加 compile 'com.github.cpiz:BubbleView:{X.X.X}'
这样貌似不行
这个X.X.X需要具体指定为某个版本吧？

**Comment by cpiz** [comment]
是的，参考release的版本号即可，目前最新是
compile 'com.github.cpiz:BubbleView:1.0.1'

**Comment by peterforme** [comment]
能把目前最新的是多少列出在readme上么  不然我们也没法看最新的是多少啊

**Comment by cpiz** [comment]
已经在README中加了链接了

Add `compile 'com.github.cpiz:BubbleView:{X.Y.Z}'` to your module-level `build.gradle`(see X.Y.Z in [Releases](https://github.com/cpiz/BubbleView/releases))
```
dependencies {
    ...
    compile 'com.github.cpiz:BubbleView:{X.Y.Z}'
}
```
