### ISSUE TITLE
文字显示不全

### ISSUE THREAD

**Issue by peterforme** [cpiz/BubbleView#8]
当文本内容为单个中文的时候（我用的是 门  这个字），发现气泡中的文本会显示不完全
这个该怎么解决

**Comment by peterforme** [comment]
![knbezklqaib gpr94s1 ma](https://cloud.githubusercontent.com/assets/4645357/23152591/e769fb58-f83d-11e6-88ff-70260ea88758.png)
最后一条记录的 门 这个字显示不全

**Comment by peterforme** [comment]
![pic](https://cloud.githubusercontent.com/assets/4645357/23152737/14e6ab0c-f83f-11e6-8792-5c71630a276f.png)
这是demo中的工程，自动指向方式中，我把每个文本的text改为 门 这个字，结果就发现显示不全了

**Comment by cpiz** [comment]
感谢反馈，验证了一下确实存在这个问题，原因是使用bb_arrowTo时不能预先判断要指向的方向，没有给箭头预留足够的空间。
临时解决办法是加上bb_arrowDirection属性来显式指定方向，这与bb_arrowTo并不冲突。终极的方案我再想一想。

**Comment by peterforme** [comment]
那你改好了后通知一下我哈
